/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-16-2011
 * 
 * XDoclet definition:
 * @struts.form name="cntUpdateForm"
 */
@SuppressWarnings("serial")
public class CntUpdateForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** shareId property */
	private Integer shareId;

	/** type property */
	private Integer type;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the shareId.
	 * @return Integer
	 */
	public Integer getShareId() {
		return shareId;
	}

	/** 
	 * Set the shareId.
	 * @param shareId The shareId to set
	 */
	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	/** 
	 * Returns the type.
	 * @return Integer
	 */
	public Integer getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}