/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-08-2011
 * 
 * XDoclet definition:
 * @struts.form name="logCommentForm"
 */
@SuppressWarnings("serial")
public class LogCommentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** logId property */
	private Integer logId;
	
	private String content;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the logId.
	 * @return Integer
	 */
	public Integer getLogId() {
		return logId;
	}

	/** 
	 * Set the logId.
	 * @param logId The logId to set
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}
}