/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-24-2011
 * 
 * XDoclet definition:
 * @struts.form name="searchForm"
 */
@SuppressWarnings("serial")
public class SearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** searchKey property */
	private String searchKey;

	/** searchType property */
	private Integer searchType;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the searchKey.
	 * @return String
	 */
	public String getSearchKey() {
		return searchKey;
	}

	/** 
	 * Set the searchKey.
	 * @param searchKey The searchKey to set
	 */
	public void setSearchKey(String searchKey) {
		this.searchKey = searchKey;
	}

	/** 
	 * Returns the searchType.
	 * @return Integer
	 */
	public Integer getSearchType() {
		return searchType;
	}

	/** 
	 * Set the searchType.
	 * @param searchType The searchType to set
	 */
	public void setSearchType(Integer searchType) {
		this.searchType = searchType;
	}
}