/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-28-2011
 * 
 * XDoclet definition:
 * @struts.form name="shareDetailForm"
 */
public class ShareDetailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** uid property */
	private Integer uid;

	/** sid property */
	private Integer sid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the uid.
	 * @return Integer
	 */
	public Integer getUid() {
		return uid;
	}

	/** 
	 * Set the uid.
	 * @param uid The uid to set
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/** 
	 * Returns the sid.
	 * @return Integer
	 */
	public Integer getSid() {
		return sid;
	}

	/** 
	 * Set the sid.
	 * @param sid The sid to set
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}
}