/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-11-2011
 * 
 * XDoclet definition:
 * @struts.form name="showPicForm"
 */
@SuppressWarnings("serial")
public class ShowPicForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private Integer id;
	
	private Integer nextPre;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return Integer
	 */
	public Integer getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNextPre() {
		return nextPre;
	}

	public void setNextPre(Integer nextPre) {
		this.nextPre = nextPre;
	}
}