/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.jhe.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-20-2011
 * 
 * XDoclet definition:
 * @struts.form name="queryForm"
 */
public class QueryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** danhao property */
	private String danhao;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the danhao.
	 * @return String
	 */
	public String getDanhao() {
		return danhao;
	}

	/** 
	 * Set the danhao.
	 * @param danhao The danhao to set
	 */
	public void setDanhao(String danhao) {
		this.danhao = danhao;
	}
}