/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.beans.ShareComment;
import com.weshare.beans.Users;
import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.CommentForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-15-2011
 * @author zhaocq
 */
public class CommentAction extends DispatchAction {
	/** 
	 * 添加评论
	 */
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommentForm cf = (CommentForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//更新Share表中的评论条数，顺便可以检查要评论的活动是否存在
		int cnt;
		String sql = "";
		sql += "update Share set CommentCount=isNull(CommentCount,0)+1 where ShareID=";
		sql += cf.getShareId();
		
		DBManager dbMgr = new DBManager();
		cnt = dbMgr.doUpdate(sql);
		if(cnt == 0){				//不存在
			err.add("result",new ActionMessage("err.action.commonDel"));
		}else{
			int userId = (Integer)(request.getSession().getAttribute("curUserId"));
			sql = "";
			sql += "insert into ShareComment (ShareID,UserID,Comment) values (";
			sql += cf.getShareId();
			sql += ",";
			sql += userId;
			sql += ",'";
			sql += cf.getContent();
			sql += "'";
			sql += ")";

			cnt = dbMgr.doUpdate(sql);
							
			if(cnt == 0){	//修改失败
				err.add("result",new ActionMessage("err.action.commonFail"));
			}else{			//修改成功
				err.add("result",new ActionMessage("err.action.commonSuccess"));
			}
		}
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
	
	/**
	 * 获取所有评论<br />
	 * 理论上应该分页显示，目前只是权宜之计
	 */
	public ActionForward getAll(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommentForm cf = (CommentForm) form;
		ActionForward af = new ActionForward();
		List<ShareComment> scList = new ArrayList<ShareComment>();
		Timestamp timeTmp;
		SimpleDateFormat dateFormat = new SimpleDateFormat(
				"yyyy-MM-dd HH:mm:ss", new Locale("zh", "cn"));
		
		ResultSet rs;
		String sql = "";
		sql += "select Users.UserID,UserName,Photo,SCID,ShareID,Comment,UpdateTime from ";
		sql += "ShareComment left join Users on (ShareComment.UserID = Users.UserID) ";
		sql += "where ShareID=";
		sql += cf.getShareId();
		sql += " order by UpdateTime asc";
		
		DBManager dbMgr = new DBManager();
		rs = dbMgr.doQuery(sql);
		try {
			while(rs.next()){
				ShareComment sc = new ShareComment();
				sc.setScId(rs.getInt("SCID"));
				
				Users user = new Users();
				user.setUserId(rs.getInt("UserID"));
				user.setPhoto(rs.getString("Photo"));
				user.setUserName(rs.getString("UserName"));
				sc.setUser(user);
				
				int curUserId = (Integer)(request.getSession().getAttribute("curUserId"));
				int owner = (curUserId == user.getUserId()) ? 1 : 0;
				sc.setOwner(owner);
				sc.setShareId(rs.getInt("ShareID"));
				sc.setComment(rs.getString("Comment"));
				
				timeTmp = rs.getTimestamp("UpdateTime");
				String updateTime = dateFormat.format(timeTmp);
				sc.setUpdateTime(updateTime);
				
				scList.add(sc);
			}
			request.setAttribute("list", scList);
			af = mapping.findForward("list");
		} catch (SQLException e) {
			request.setAttribute("shareId", cf.getShareId());
		}
		return af;
	}
	
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CommentForm cf = (CommentForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//检查要评论的活动是否存在
		int cnt;
		String sql = "";
		sql += "select SCID from ShareComment where SCID=";
		sql += cf.getScId();
		
		DBManager dbMgr = new DBManager();
		ResultSet rs = dbMgr.doQuery(sql);
		try {
			if(!rs.next()){				//不存在
				err.add("result",new ActionMessage("err.action.commonDel"));
			}else{
				sql = "";
				sql += "delete from ShareComment where SCID=";
				sql += cf.getScId();

				cnt = dbMgr.doDelete(sql);
								
				if(cnt == 0){	//删除失败
					err.add("result",new ActionMessage("err.action.commonFail"));
				}else{			//删除成功
					err.add("result",new ActionMessage("err.action.commonSuccess"));
				}
			}
		} catch (SQLException e) {
			err.add("result",new ActionMessage("err.action.commonFail"));
		}
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}

}