/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;
import com.weshare.struts.form.GetNewsForm;
import com.weshare.util.Common;

/** 
 * MyEclipse Struts
 * Creation date: 09-18-2011
 * 
 * XDoclet definition:
 * @struts.action path="/getNews" name="getNewsForm" input="/formValidate/getNews.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="success" path="/showNews.jsp"
 */
public class GetNewsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 获取下一页新鲜事
	 */
	public ActionForward getNextPage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetNewsForm gnf = (GetNewsForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();

		int curUserId = (Integer) (request.getSession().getAttribute("curUserId"));
		int pageSize = gnf.getPageSize();
		int startID = gnf.getLastShareId();
		int type = gnf.getType();
		
		boolean bRet = Common.getShareList(request, curUserId, type, startID, pageSize);
		if(bRet == false){				//获取失败
			err.add("commonErr", new ActionMessage("err.action.commonFail"));
			// 转向一个通用的错误处理页面
			af = mapping.findForward("failPage");
		}else{
			af = mapping.findForward("success");
		}
		return af;
	}
}