/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.LogForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2011
 * 
 * XDoclet definition:
 * @struts.action path="/log" name="logForm" parameter="m" scope="request" validate="true"
 * @struts.action-forward name="success" path="/showLog.do"
 */
public class LogAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LogForm logForm = (LogForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//删除日志
		int cnt;
		String sql = "";
		sql += "delete from ShareLog where SLID=";
		sql += logForm.getId();
		
		DBManager dbMgr = new DBManager();
		cnt = dbMgr.doDelete(sql);
		if(cnt == 0){				//不存在
			err.add("result",new ActionMessage("err.action.commonDel"));
		}else{
			err.add("result",new ActionMessage("err.action.commonSuccess"));
		}
		
		//删除此日志的评论
		//此部分交给触发器操作
		af = mapping.findForward("del");
		saveErrors(request, err);
		return af;
	}
}