/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.LogCommentForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-08-2011
 * 
 * XDoclet definition:
 * @struts.action path="/logComment" name="logCommentForm" parameter="m" scope="request" validate="true"
 * @struts.action-forward name="success" path="/actionResult.jsp"
 */
public class LogCommentAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LogCommentForm logCommentForm = (LogCommentForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//更新ShareLog表中的评论条数，顺便可以检查要评论的活动是否存在
		int cnt;
		String sql = "";
		sql += "update ShareLog set CommentCount=isNull(CommentCount,0)+1 where SLID=";
		sql += logCommentForm.getLogId();
		
		DBManager dbMgr = new DBManager();
		cnt = dbMgr.doUpdate(sql);
		if(cnt == 0){				//不存在
			err.add("result",new ActionMessage("err.action.commonDel"));
		}else{
			int userId = (Integer)(request.getSession().getAttribute("curUserId"));
			sql = "";
			sql += "insert into ShareLogComment (ShareLogID,UserID,Comment) values (";
			sql += logCommentForm.getLogId();
			sql += ",";
			sql += userId;
			sql += ",'";
			sql += logCommentForm.getContent();
			sql += "')";

			cnt = dbMgr.doUpdate(sql);
							
			if(cnt == 0){	//修改失败
				err.add("result",new ActionMessage("err.action.commonFail"));
			}else{			//修改成功
				err.add("result",new ActionMessage("err.action.commonSuccess"));
			}
		}
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
}