/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.PicForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2011
 * 
 * XDoclet definition:
 * @struts.action path="/pic" name="picForm" parameter="m" scope="request" validate="true"
 * @struts.action-forward name="success" path="/actionResult.jsp"
 */
public class PicAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 删除一个照片
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PicForm picForm = (PicForm) form;// TODO Auto-generated method stub
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//删除照片
		int cnt;
		String sql = "";
		sql += "delete from SharePhoto where SPID=";
		sql += picForm.getId();
		
		DBManager dbMgr = new DBManager();
		cnt = dbMgr.doDelete(sql);
		if(cnt == 0){				//不存在
			err.add("result",new ActionMessage("err.action.commonDel"));
		}else{
			err.add("result",new ActionMessage("err.action.commonSuccess"));
		}
		
		//删除该照片的所有评论
		//此部分改为触发器操作
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
	
	/**
	 * 将照片设为封面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward setIndex(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PicForm picForm = (PicForm) form;// TODO Auto-generated method stub
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//直接设置照片封面
		int cnt = 0;
		String sql = "";
		sql += "update SharePhoto set indexPic=1 where SPID=";
		sql += picForm.getId();
		
		DBManager dbMgr = new DBManager();
		cnt = dbMgr.doUpdate(sql);
		if(cnt == 0){				//设置失败，可能是数据库写入失败，也可能是该照片已经不存在
			err.add("result",new ActionMessage("err.action.commonDel"));
		}else{
			err.add("result",new ActionMessage("err.action.commonSuccess"));
		}
		//设置完毕后需要取消原来的封面
		//此部分使用触发器操作
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
}