/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.PicCommentForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2011
 * 
 * XDoclet definition:
 * @struts.action path="/picComment" name="picCommentForm" parameter="m" scope="request" validate="true"
 * @struts.action-forward name="success" path="/actionResult.jsp"
 */
public class PicCommentAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PicCommentForm picCommentForm = (PicCommentForm) form;// TODO Auto-generated method stub
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		//检查要评论的活动是否存在
		String sql = "";
		sql += "select SPID from SharePhoto where SPID = ";
		sql += picCommentForm.getPicId();
		
		DBManager dbMgr = new DBManager();
		ResultSet rs = dbMgr.doQuery(sql);
		int cnt = 0;
		try {
			if(!rs.next()){				//不存在
				err.add("result",new ActionMessage("err.action.commonDel"));
			}else{
				int userId = (Integer)(request.getSession().getAttribute("curUserId"));
				sql = "";
				sql += "insert into SharePhotoComment (SharePhotoID,UserID,Comment) values (";
				sql += picCommentForm.getPicId();
				sql += ",";
				sql += userId;
				sql += ",'";
				sql += picCommentForm.getContent();
				sql += "')";

				cnt = dbMgr.doUpdate(sql);
								
				if(cnt == 0){	//插入失败
					err.add("result",new ActionMessage("err.action.commonFail"));
				}else{			//插入成功
					err.add("result",new ActionMessage("err.action.commonSuccess"));
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
}