/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.RegForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2011
 * 
 * XDoclet definition:
 * @struts.action path="/reg" name="regForm" input="/reg1.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/reg.jsp"
 * @struts.action-forward name="success" path="/login.jsp"
 */
public class RegAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@SuppressWarnings("null")
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegForm regForm = (RegForm) form;
		ActionForward af = new ActionForward();
		
		//检查是否有重名
		String sql = "select UserID from Users where UserName='" +
		regForm.getUsername() + "' and Password = '" +
		regForm.getPassword() + "'";
		DBManager dbMgr = new DBManager();
		ResultSet rs = dbMgr.doQuery(sql);
		
		if(rs != null){
			//存在重名，设置错误信息
			ActionErrors err=new ActionErrors();
			err.add("usernameErr", new ActionMessage("err.reg.rename",regForm.getUsername()));
			af = mapping.findForward("fail");
		}else{
			//可以注册，添加注册信息
			sql = "insert into Users (UserName,Password,Mail) values ('" +
					regForm.getUsername() + "','" +
					regForm.getPassword() + "','" +
					regForm.getMail() + "')";
			dbMgr.doInsert(sql);
			af = mapping.findForward("success");
		}

		try {
			rs = null;
			rs.close();
			dbMgr.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return af;
	}
}