/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 08-27-2011
 * 
 * XDoclet definition:
 * 
 * @struts.form name="addShareForm"
 */
@SuppressWarnings("serial")
public class AddShareForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** startTime property */
	private String startTime;

	/** activeDetail property */
	private String activeDetail;

	/** activeLocation property */
	private String activeLocation;

	/** endTime property */
	private String endTime;

	/** typeValue property */
	private Integer typeValue;

	private String lat;

	private String lng;

	private Integer schoolId;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors err = new ActionErrors();
		if(this.typeValue == 0){
			err.add("errors", new ActionMessage("err.addShare.typeEmpty"));
			return err;
		}
		if(this.startTime == "" || this.startTime == null){
			err.add("errors", new ActionMessage("err.addShare.startTimeEmpty"));
			return err;
		}
		if(this.endTime == "" || this.endTime == null){
			err.add("errors", new ActionMessage("err.addShare.endTimeEmpty"));
			return err;
		}
		if(this.activeLocation == "" || this.activeLocation == null){
			err.add("errors", new ActionMessage("err.addShare.activeLocationEmpty"));
			return err;
		}
		if(this.lat == "" || this.lat == null || this.lng == "" || this.lng == null){
			err.add("errors", new ActionMessage("err.addShare.latLngErr"));
			return err;
		}
		if(this.activeDetail == "" || this.activeDetail == null){
			err.add("errors", new ActionMessage("err.addShare.activeDetailEmpty"));
			return err;
		}
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the startTime.
	 * 
	 * @return String
	 */
	public String getStartTime() {
		return startTime;
	}

	/**
	 * Set the startTime.
	 * 
	 * @param startTime
	 *            The startTime to set
	 */
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	/**
	 * Returns the activeDetail.
	 * 
	 * @return String
	 */
	public String getActiveDetail() {
		return activeDetail;
	}

	/**
	 * Set the activeDetail.
	 * 
	 * @param activeDetail
	 *            The activeDetail to set
	 */
	public void setActiveDetail(String activeDetail) {
		this.activeDetail = activeDetail;
	}

	/**
	 * Returns the activeLocation.
	 * 
	 * @return String
	 */
	public String getActiveLocation() {
		return activeLocation;
	}

	/**
	 * Set the activeLocation.
	 * 
	 * @param activeLocation
	 *            The activeLocation to set
	 */
	public void setActiveLocation(String activeLocation) {
		this.activeLocation = activeLocation;
	}

	/**
	 * Returns the endTime.
	 * 
	 * @return String
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * Set the endTime.
	 * 
	 * @param endTime
	 *            The endTime to set
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * Returns the typeValue.
	 * 
	 * @return Integer
	 */
	public Integer getTypeValue() {
		return typeValue;
	}

	/**
	 * Set the typeValue.
	 * 
	 * @param typeValue
	 *            The typeValue to set
	 */
	public void setTypeValue(Integer typeValue) {
		this.typeValue = typeValue;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLng() {
		return lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public Integer getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

}