/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-15-2011
 * 
 * XDoclet definition:
 * @struts.form name="commentForm"
 */
@SuppressWarnings("serial")
public class CommentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** content property */
	private String content;

	/** shareId property */
	private Integer shareId;
	
	private Integer scId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the shareId.
	 * @return Integer
	 */
	public Integer getShareId() {
		return shareId;
	}

	/** 
	 * Set the shareId.
	 * @param shareId The shareId to set
	 */
	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public Integer getScId() {
		return scId;
	}

	public void setScId(Integer scId) {
		this.scId = scId;
	}
}