/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-18-2011
 * 
 * XDoclet definition:
 * @struts.form name="getNewsForm"
 */
@SuppressWarnings("serial")
public class GetNewsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** lastShareId property */
	private Integer lastShareId;
	private Integer pageSize;
	private Integer type;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the lastShareId.
	 * @return Integer
	 */
	public Integer getLastShareId() {
		return lastShareId;
	}

	/** 
	 * Set the lastShareId.
	 * @param lastShareId The lastShareId to set
	 */
	public void setLastShareId(Integer lastShareId) {
		this.lastShareId = lastShareId;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
}