/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-14-2011
 * 
 * XDoclet definition:
 * @struts.form name="modifyShareForm"
 */
@SuppressWarnings("serial")
public class ModifyShareForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** sid property */
	private Integer sid;

	/** status property */
	private Integer status;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the sid.
	 * @return Integer
	 */
	public Integer getSid() {
		return sid;
	}

	/** 
	 * Set the sid.
	 * @param sid The sid to set
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/** 
	 * Returns the status.
	 * @return Integer
	 */
	public Integer getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}