/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-04-2011
 * 
 * XDoclet definition:
 * @struts.form name="regForm"
 */
@SuppressWarnings("serial")
public class RegForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** mail property */
	private String mail;

	/** username property */
	private String username;

	/** ckPassword property */
	private String ckPassword;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors err = new ActionErrors();
		if((this.username == null) || (this.username.equals(""))){
			err.add("usernameErr", new ActionMessage("err.reg.username",username));	
		}
		if((this.password == null) || (this.password.equals(""))){
			err.add("passwordErr", new ActionMessage("err.reg.password",password));	
		}
		if(!this.password.equals(ckPassword)){
			err.add("passwordErr", new ActionMessage("err.reg.ckPassword",ckPassword));
		}
		if((this.mail == null) || (this.mail.equals(""))){
			err.add("mail", new ActionMessage("err.reg.mail",mail));
		}
		return err;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the mail.
	 * @return String
	 */
	public String getMail() {
		return mail;
	}

	/** 
	 * Set the mail.
	 * @param mail The mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the ckPassword.
	 * @return String
	 */
	public String getCkPassword() {
		return ckPassword;
	}

	/** 
	 * Set the ckPassword.
	 * @param ckPassword The ckPassword to set
	 */
	public void setCkPassword(String ckPassword) {
		this.ckPassword = ckPassword;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}