/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.Timestamp;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.AddShareForm;

/**
 * MyEclipse Struts Creation date: 08-27-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/addShare" name="addShareForm" input="/myPage.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/actionResult.jsp"
 */
public class AddShareAction extends Action {
	/*
	 * 
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddShareForm asForm = (AddShareForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();

		// 将String类型的时间转换为Timestamp类型
		String s = asForm.getStartTime() + " 00:00:00";		//将时间格式加上时分秒
		String e = asForm.getEndTime() + " 00:00:00";		//将时间格式加上时分秒
		Timestamp start = Timestamp.valueOf(s);
		Timestamp end = Timestamp.valueOf(e);

		HttpSession session = request.getSession();
		int userId = (Integer) session.getAttribute("curUserId");

		String sql = "insert into Share ("
				+ "UserID,TypeID,StartDate,EndDate,Location,"
				+ "Detail,Longitude,Latitude,SchoolID) "
				+ "values ("
				+ userId
				+ ","
				+ asForm.getTypeValue()
				+ ",'"
				+ start
				+ "','"
				+ end
				+ "','"
				+ asForm.getActiveLocation()
				+ "','"
				+ asForm.getActiveDetail()
				+ "','"
				+ asForm.getLng()
				+ "','"
				+ asForm.getLat()
				+ "',"
				+ asForm.getSchoolId()
				+ ")";
		DBManager dbMgr = new DBManager();
		int cnt = dbMgr.doInsert(sql);
		
		//插入失败
		if(cnt == 0){
			err.add("result",new ActionMessage("err.action.commonFail"));
		}else{			//插入成功
			err.add("result",new ActionMessage("err.action.commonSuccess"));
		}
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
}