/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.beans.Users;
import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.GetShareInfoForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-14-2011
 */
public class GetShareInfoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 获取参加活动的人员
	 */
	public ActionForward getJoinList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetShareInfoForm gsiForm = (GetShareInfoForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		String sql = "";
		sql += "select Users.UserID, Users.UserName,Users.Photo from " +
				"[Join] left join Users on ([Join].UserID = Users.UserID) " +
				"where ShareID=";
		sql += gsiForm.getSid();
		sql += " order by JoinTime desc";
		
		DBManager dbMgr = new DBManager();
		ResultSet rs = dbMgr.doQuery(sql);
		
		List <Users> usersList = new ArrayList<Users>();
		try {
			while(rs.next()){
				Users user = new Users();
				user.setUserId(rs.getInt("UserID"));
				user.setUserName(rs.getString("UserName"));
				user.setPhoto(rs.getString("Photo"));
				usersList.add(user);
			}
		} catch (SQLException e) {
			err.add("queryError", new ActionMessage("err.db.queryError"));
		}
		
		if(err.isEmpty() == false){
			saveErrors(request,err);
		}
		request.setAttribute("users", usersList);
		af = mapping.findForward("success");
		return af;
	}
	
	/**
	 * 获取围观活动的人员
	 */
	public ActionForward getViewList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GetShareInfoForm gsiForm = (GetShareInfoForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		String sql = "";
		sql += "select Users.UserID, Users.UserName,Users.Photo from " +
				"[View] left join Users on ([View].UserID = Users.UserID) " +
				"where ShareID=";
		sql += gsiForm.getSid();
		sql += " order by ViewTime desc";
		
		DBManager dbMgr = new DBManager();
		ResultSet rs = dbMgr.doQuery(sql);
		
		List <Users> usersList = new ArrayList<Users>();
		try {
			while(rs.next()){
				Users user = new Users();
				user.setUserId(rs.getInt("UserID"));
				user.setUserName(rs.getString("UserName"));
				user.setPhoto(rs.getString("Photo"));
				usersList.add(user);
			}
		} catch (SQLException e) {
			err.add("queryError", new ActionMessage("err.db.queryError"));
		}
		
		if(err.isEmpty() == false){
			saveErrors(request,err);
		}
		request.setAttribute("users", usersList);
		af = mapping.findForward("success");
		return af;
	}
}