/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.weshare.beans.School;
import com.weshare.beans.Users;
import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.HomeForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/home" name="homeForm" input="/login.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/homeErr.jsp"
 * @struts.action-forward name="success" path="/home.jsp"
 */
public class HomeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HomeForm homeForm = (HomeForm) form;
		
		
		HttpSession session = request.getSession();
		Integer curUserId = (Integer)session.getAttribute("curUserId");
		DBManager db = new DBManager();
		ResultSet userRs;
		String sql = "";
		int curId = homeForm.getId();

		//如果要请求的页面不是当前用户页面，则重新读取该用户信息
		//否则直接读取session中当前用户的信息即可
		if(curUserId != curId){
			try {
				sql = "select UserID,UserName,Photo,Users.SchoolID,SchoolName from Users left join School on (Users.SchoolID = School.SchoolID) where UserID="
						+ curId;
				userRs = db.doQuery(sql);
				if (userRs.next()) {
					Users users = new Users();
					users.setUserId(userRs.getInt("UserID"));
					users.setUserName(userRs.getString("UserName"));
					users.setPhoto(userRs.getString("Photo"));
					School school = new School();
					school.setId(userRs.getInt("SchoolID"));
					school.setSchoolName(userRs.getString("SchoolName"));
					users.setSchool(school);
					request.setAttribute("user", users);
				}
			} catch (SQLException e) {
				
			}
		}else{
			request.setAttribute("user", session.getAttribute("curUser"));
		}
		
		//读取个人参加活动的总数
		sql = "select count(Share.ShareID) sCnt,count(Join.ShareID) jCnt," ;
		sql += "count(View.ShareID) vCnt ";
		sql += "from Share,Join,View where Share.UserID=";
		sql += curId;
		sql += " and Join.UserID=";
		sql += curId;
		sql += " and View.UserID=";
		sql += curId;
		userRs = db.doQuery(sql);
		if(userRs.next()){
			request.setAttribute("sCnt", userRs.getInt("sCnt"));
			request.setAttribute("jCnt", userRs.getInt("jCnt"));
			request.setAttribute("vCnt", userRs.getInt("vCnt"));
		}
		return null;
	}
}