/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.weshare.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.weshare.jdbc.dbconn.DBManager;
import com.weshare.struts.form.ModifyShareForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-14-2011
 * 
 * XDoclet definition:
 * @struts.action path="/modifyShare" name="modifyShareForm" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="success" path="/actionResult.jsp"
 */
public class ModifyShareAction extends DispatchAction {
	/** 
	 * 修改活动状态。<br />
	 * 0：活动报名阶段；1：结束报名；2：结束活动
	 */
	public ActionForward changeStatus(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifyShareForm msForm = (ModifyShareForm) form;
		ActionForward af = new ActionForward();
		ActionMessages err = new ActionMessages();
		
		String sql = "";
		sql += "update Share set Status = ";
		sql += msForm.getStatus();
		sql += " where ShareID = ";
		sql += msForm.getSid();

		DBManager dbMgr = new DBManager();
		int cnt = dbMgr.doUpdate(sql);
		
		//修改失败
		if(cnt == 0){
			err.add("result",new ActionMessage("err.action.commonFail"));
		}else{			//修改成功
			err.add("result",new ActionMessage("err.action.commonSuccess"));
		}
		af = mapping.findForward("success");
		saveErrors(request, err);
		return af;
	}
}