/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.jhe.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.jhe.odbc.dbconn.DBManager;
import com.jhe.struts.bean.Employee;
import com.jhe.struts.form.EmployeeForm;

/**
 * MyEclipse Struts Creation date: 12-20-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/employee" name="employeeForm" input="/employee.jsp"
 *                parameter="m" scope="request" validate="true"
 * @struts.action-forward name="success" path="/employee.jsp"
 */
public class EmployeeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward get(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String sql = "select ID,PaiJianYuan,Phone from Employee order by ID desc";
		DBManager db = new DBManager();
		ResultSet rs = db.doQuery(sql);
		List<Employee> list = new ArrayList<Employee>();
		try {
			while (rs.next()) {
				Employee e = new Employee();
				e.setId(rs.getInt("ID"));
				e.setPaijianyuan(rs.getString("PaiJianYuan"));
				e.setPhone(rs.getString("Phone"));
				list.add(e);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		request.setAttribute("employee", list);
		db.close();
		return mapping.findForward("success");
	}

	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EmployeeForm employeeForm = (EmployeeForm) form;
		String sql = "delete from Employee where id=" + employeeForm.getId();
		DBManager db = new DBManager();
		int cnt = db.doDelete(sql);
		try {
			PrintWriter out = response.getWriter();
			out.print(cnt);
		} catch (IOException e) {
			e.printStackTrace();
		}
		db.close();
		return null;
	}

	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EmployeeForm employeeForm = (EmployeeForm) form;
		String sql = "insert into Employee (PaiJianYuan,Phone) values ('"
				+ employeeForm.getPaijianyuan() + "','"
				+ employeeForm.getPhone() + "')";
		DBManager db = new DBManager();
		int cnt = db.doDelete(sql);
		try {
			PrintWriter out = response.getWriter();
			out.print(cnt);
		} catch (IOException e) {
			e.printStackTrace();
		}
		db.close();
		return null;
	}
}