/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.jhe.struts.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jhe.odbc.dbconn.DBManager;
import com.jhe.struts.form.PaijianForm;

/**
 * MyEclipse Struts Creation date: 12-16-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/paijian" name="paijianForm" input="/paijian.jsp"
 *                scope="request" validate="true"
 */
public class PaijianAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaijianForm paijianForm = (PaijianForm) form;
		try {
			PrintWriter out = response.getWriter();
			String dh = paijianForm.getDanhao();
			String pjy = paijianForm.getPaijianyuan();
			if (dh.trim().equals("") || pjy.trim().equals("")) {
				out.print("0");
			} else {
				String sql = "insert into PaiJian (DanHao,PaiJianYuan) values ('" + dh + "'," + pjy + ")";
				DBManager db = new DBManager();
				int cnt = db.doInsert(sql);
				out.print(cnt);
				db.close();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
}