/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.jhe.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jhe.odbc.dbconn.DBManager;
import com.jhe.struts.bean.Employee;

/** 
 * MyEclipse Struts
 * Creation date: 12-16-2011
 * 
 * XDoclet definition:
 * @struts.action path="/prePaiJian" name="prePaiJianForm" input="/form/prePaiJian.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/paijian.jsp"
 */
public class PrePaiJianAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String sql = "select ID,PaiJianYuan from Employee order by ID asc";
		DBManager db = new DBManager();
		ResultSet rs = db.doQuery(sql);
		List<Employee> es = new ArrayList<Employee>();
		try {
			while(rs.next()){
				Employee e = new Employee();
				e.setId(rs.getInt("ID"));
				e.setPaijianyuan(rs.getString("PaiJianYuan"));
				es.add(e);
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		request.setAttribute("es", es);
		db.close();
		return mapping.findForward("success");
	}
}