/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.jhe.struts.action;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.jhe.odbc.dbconn.DBManager;
import com.jhe.struts.bean.Employee;
import com.jhe.struts.bean.JinGang;
import com.jhe.struts.bean.PaiJian;
import com.jhe.struts.bean.QianShou;
import com.jhe.struts.form.QueryForm;

/**
 * MyEclipse Struts Creation date: 12-20-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/query" name="queryForm" input="/query.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/query.jsp"
 */
public class QueryAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		QueryForm queryForm = (QueryForm) form;
		String sql = "select DanHao,UpdateTime from JinGang where DanHao='"
				+ queryForm.getDanhao() + "'";
		DBManager db = new DBManager();
		ResultSet rs = db.doQuery(sql);
		JinGang jg = new JinGang();
		PaiJian pj = new PaiJian();
		QianShou qs = new QianShou();
		try {
			if (rs.next()) {
				jg.setDanhao(rs.getString("DanHao"));
				jg.setUpdateTime(rs.getString("UpdateTime"));
				request.setAttribute("jg", jg);
				sql = "select PaiJian.DanHao,PaiJian.PaiJianTime,Employee.PaiJianYuan,Employee.Phone "
						+ "from PaiJian left join Employee on(PaiJian.PaiJianYuan=Employee.ID) where DanHao='"
						+ queryForm.getDanhao() + "'";
				ResultSet pjRs = db.doQuery(sql);
				if (pjRs.next()) {
					pj.setDanhao(pjRs.getString("DanHao"));
					pj.setUpdateTime(pjRs.getString("PaiJianTime"));
					Employee e = new Employee();
					e.setPaijianyuan(pjRs.getString("PaiJianYuan"));
					e.setPhone(pjRs.getString("Phone"));
					pj.setE(e);
					request.setAttribute("pj", pj);
					sql = "select DanHao,QianShouRen,QianShouTime from QianShou where DanHao='"
							+ queryForm.getDanhao() + "'";
					ResultSet qsRs = db.doQuery(sql);
					if(qsRs.next()){
						qs.setDanhao(qsRs.getString("DanHao"));
						qs.setQianshouren(qsRs.getString("QianShouRen"));
						qs.setUpdateTime(qsRs.getString("QianShouTime"));
						request.setAttribute("qs", qs);
					}
				}
			}else{
				request.setAttribute("noResult", "noResult");
				request.setAttribute("dh", queryForm.getDanhao());
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		db.close();
		return mapping.findForward("success");
	}
}